name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mkdir $GITHUB_WORKSPACE/docs-build

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: pnpm/action-setup@v2
      with:
        version: 8.2.0
        run_install: false

    - uses: actions/checkout@v3
      with:
        path: 'docs-build/docs'

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install documentation
      run: |
        cd $GITHUB_WORKSPACE/docs-build/docs
        pnpm install

    - name: Build documentation
      run: |
        cd $GITHUB_WORKSPACE/docs-build/docs
        npm run build

    - name: Clear public_html
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          rm -rf ~/public_html

    - name: Deploy doc build onto website
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "./docs-build/docs/build"
        target: "~/public_html"
        strip_components: 4
